spring.application.name=sabacc-backend
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
rsa.rsa-private-key=classpath:certs/private.pem
rsa.rsa-public-key=classpath:certs/public.pem
# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Datasource
spring.datasource.url=jdbc:h2:file:./backend/src/main/resources/data/sabacc-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dev
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
